name: create_pages_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  json_annotation: ^4.7.0
  lottie: 1.4.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

